services:

  bannou:
    labels:
      - "traefik.http.routers.auth-service-local.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.auth-service-local.entrypoints=web"
      - "traefik.http.routers.auth-service-local.middlewares=auth-prefix@docker"
      - "traefik.http.routers.auth-service-local.service=auth-service"
      - "traefik.http.routers.connect-service-local.rule=Host(`connect.localhost`)"
      - "traefik.http.routers.connect-service-local.entrypoints=web"
      - "traefik.http.routers.connect-service-local.middlewares=connect-prefix@docker"
      - "traefik.http.routers.connect-service-local.service=connect-service"
