openapi: 3.0.3
info:
  title: Relationship Type Service Configuration
  description: "Configuration schema for Relationship Type service.\nProperties are bound to environment variables with BANNOU_
    prefix."
  version: 1.0.0
paths: {}
x-service-configuration:
  properties:
    Enabled:
      type: boolean
      description: Enable/disable Relationship Type service
      default: true
