name: 'Active PR CI Tests'
on:

  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: '7.0.202'
  DOTNET_INSTALL_DIR: './.dotnet'

jobs:

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout Repo

      - name: Run Service Tests
        run: docker-compose -f "./provisioning/docker-compose.yml" -f "./provisioning/docker-compose.ci.yml" up --build --exit-code-from=bannou-tester
        env:
          TESTING_SERVICE_ENABLED: true
